oracle/oci-volume-provisioner

README.md

Adds go report card badge to README.md

Add go report card badge to README.md

---

pkg/provisioner/provisioner.go

Fix assignment warning (Go report card)

Fix warning: ann assigned and not used

---

pkg/provisioner/provisioner.go

Made the default hard-coded timeout more lenient (3 minutes).

Update default timeout.

---

manifests/example-claim-ffsw.yaml

FFSW can be shared between multiple nodes.

Update example claim for FFSW to be ReadWriteMany

---

README.md

This changes implements some minor updates to the project README to mention the recently added support for FFSW.

Update README to mention support for FFSW

---

Makefile
manifests/example-claim-ext3.yaml
manifests/example-claim-ffsw.yaml
manifests/example-claim.template
test/system/README.md
test/system/runner.py

Updated the system tests such that they are able to be run on arbitrary Kubernetes clusters (i.e. they are now not tied to specific regions).

System test update to support all clusters

---

Makefile
manifests/storage-class-ffsw.yaml
test/system/runner.py
wercker.yml

Remove FFSW support after architecture review with FFSW team.

Remove references to FFSW

---

test/system/runner.py

If the system test image is run with no arguments, then we now no longer wait for the volume provisioner to be in a running state, i.e. we assume it is already running in the cluster. This will only be done if we are also installing the provisioner.

System test image fix.

---

pkg/oci/client/client.go
pkg/oci/client/config.go
pkg/oci/client/config_validate.go
pkg/oci/client/config_validate_test.go
pkg/provisioner/core/provisioner.go
pkg/provisioner/core/utils.go

This change adds support for instance principal authentication.

Add support for authentication via instance principals.

---

Makefile

Update Makefile to allow running the provisioner locally. 
`GOOS=darwin make run-dev`

Update Makefile to allow running provisioner locally

---

test/system/runner.py

Initial integration for the Sonobuoy tool.
Small changes to the test script. If configured, copy the test logs and completion file to target location in '/tmp/results'. Will create this path if it does not yet exist, and overwrite results if they do.
Also adds a final success/failure to final line of log output to easily determine if all the tests succeeded.

Sonobuoy output

---

Makefile

Fix incorrect region environment variable

---

test/system/run-test-image.yaml.template

Tighten RBAC rules for test image runner

---

test/system/run-test-image.yaml.template

Adds missing "create" verb to secret resource RBAC rule.

Add create verb to secret resource RBAC rule

---

test/system/run-test-image.yaml.template

Fix RBAC to allow test image runner to list nodes.

Fix RBAC to allow tests to list nodes

---

test/system/runner.py

Small changes to produce canary test output file if configured.

Added canary test json file support.

---

pkg/provisioner/block/block.go
pkg/provisioner/errors.go

Check whether error is a NotFound error and stop trying to delete the volume for that case.
Addresses: https://jira-sd.mc1.oracleiaas.com/browse/OKE-480

Repeated deletion of deleted volumes fix

---

pkg/oci/client/client.go
pkg/provisioner/block/block.go
pkg/provisioner/core/provisioner.go
pkg/provisioner/core/utils.go
pkg/provisioner/fss/fss.go
pkg/provisioner/fss/fss_test.go

Remove context from provisioner client structure

---

pkg/provisioner/block/block.go
pkg/provisioner/fss/fss.go

Add mount options to PV from storage class

---

pkg/provisioner/core/provisioner.go
pkg/provisioner/fss/fss.go
pkg/provisioner/fss/fss_test.go

Addresses: Missing LabelZoneRegion #166

Add label zone region

---

pkg/provisioner/block/block.go
pkg/provisioner/fss/fss.go
pkg/provisioner/utils.go

Fixes error in PR #107 for fix #99

Fix volume name prefix

---

pkg/provisioner/fss/fss.go

Add OS dependency
